"""Updated User model

Revision ID: 3eb8fe26e47a
Revises: bc8ce9e28add
Create Date: 2025-04-01 18:53:41.611940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb8fe26e47a'
down_revision = 'bc8ce9e28add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('i_admin')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i_admin', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
