"""Renamed password_hash to password

Revision ID: c7a8b4be80f2
Revises: 3eb8fe26e47a
Create Date: 2025-04-09 11:57:26.899564

"""
from alembic import op
import sqlalchemy as sa

from alembic import op

def upgrade():
    # Rename the column
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash', new_column_name='password')

def downgrade():
    # Revert the column name change
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password', new_column_name='password_hash')



# revision identifiers, used by Alembic.
revision = 'c7a8b4be80f2'
down_revision = '3eb8fe26e47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
